In [14]:
import numpy as np

def a_fraction(n):
    """
    Calcula la matriz de resultados con los índices, pares (p, l) y el valor de `ai`.

    Args:
        n (array-like): Array de valores a procesar.

    Returns:
        numpy.ndarray: Matriz con las columnas [idx, p, l, ai].
    """
    n = np.array(n)  # Asegurarse de que 'n' sea un array de numpy
    results = []  # Lista para almacenar los resultados

    for p in range(len(n)):
        for l in range(p, len(n)):
            nj, nk = n[p], n[l]
            njk = nj + nk
            idx = np.searchsorted(n, njk, side="right") - 1  # Encontrar índice del intervalo
            if idx >= 0 and idx < len(n) - 1:
                if njk == n[idx]:
                    ai = 0.0
                else:
                    ai = (n[idx + 1] - (n[p] + n[l])) / (n[idx + 1] - n[idx])
                results.append((idx, p, l, ai))  # Agregar resultado a la lista

    return np.array(results, dtype=object)  # Convertir la lista en un array NumPy

# Ejemplo de uso
nh = [1, 5, 15, 25, 35, 40, 75, 100]
result_matrix = a_fraction(nh)

print(result_matrix)


[[0 0 0 0.75]
 [1 0 1 0.9]
 [2 0 2 0.9]
 [3 0 3 0.9]
 [4 0 4 0.8]
 [5 0 5 0.9714285714285714]
 [6 0 6 0.96]
 [1 1 1 0.5]
 [2 1 2 0.5]
 [3 1 3 0.5]
 [5 1 4 0.0]
 [5 1 5 0.8571428571428571]
 [6 1 6 0.8]
 [3 2 2 0.5]
 [5 2 3 0.0]
 [5 2 4 0.7142857142857143]
 [5 2 5 0.5714285714285714]
 [6 2 6 0.4]
 [5 3 3 0.7142857142857143]
 [5 3 4 0.42857142857142855]
 [5 3 5 0.2857142857142857]
 [5 4 4 0.14285714285714285]
 [6 4 5 0.0]
 [6 5 5 0.8]]


In [27]:
def b_fraction_prima(result_a):
    b = np.copy(result_a)
    b[:,3] = 1.0 - b[:, 3]

    return b

In [28]:
b_fraction_prima(result_matrix)

array([[0, 0, 0, 0.25],
       [1, 0, 1, 0.09999999999999998],
       [2, 0, 2, 0.09999999999999998],
       [3, 0, 3, 0.09999999999999998],
       [4, 0, 4, 0.19999999999999996],
       [5, 0, 5, 0.02857142857142858],
       [6, 0, 6, 0.040000000000000036],
       [1, 1, 1, 0.5],
       [2, 1, 2, 0.5],
       [3, 1, 3, 0.5],
       [5, 1, 4, 1.0],
       [5, 1, 5, 0.1428571428571429],
       [6, 1, 6, 0.19999999999999996],
       [3, 2, 2, 0.5],
       [5, 2, 3, 1.0],
       [5, 2, 4, 0.2857142857142857],
       [5, 2, 5, 0.4285714285714286],
       [6, 2, 6, 0.6],
       [5, 3, 3, 0.2857142857142857],
       [5, 3, 4, 0.5714285714285714],
       [5, 3, 5, 0.7142857142857143],
       [5, 4, 4, 0.8571428571428572],
       [6, 4, 5, 1.0],
       [6, 5, 5, 0.19999999999999996]], dtype=object)

In [55]:
def b_fraction(a_results):
    # Filtrar las filas donde el primer elemento no sea 0
    filtered_results = a_results[a_results[:, 0] != 0]

    # Crear una copia para aplicar las transformaciones
    b = np.copy(filtered_results)

    # Incrementar el primer elemento en 1 y modificar el cuarto elemento
    b[:, 0] = b[:, 0] + 1  # Incrementar el primer elemento
    b[:, 3] = 1.0 - b[:, 3]  # Restar el cuarto elemento de 1.0

    return b


In [56]:
b_fraction(result_matrix)

array([[2, 0, 1, 0.09999999999999998],
       [3, 0, 2, 0.09999999999999998],
       [4, 0, 3, 0.09999999999999998],
       [5, 0, 4, 0.19999999999999996],
       [6, 0, 5, 0.02857142857142858],
       [7, 0, 6, 0.040000000000000036],
       [2, 1, 1, 0.5],
       [3, 1, 2, 0.5],
       [4, 1, 3, 0.5],
       [6, 1, 4, 1.0],
       [6, 1, 5, 0.1428571428571429],
       [7, 1, 6, 0.19999999999999996],
       [4, 2, 2, 0.5],
       [6, 2, 3, 1.0],
       [6, 2, 4, 0.2857142857142857],
       [6, 2, 5, 0.4285714285714286],
       [7, 2, 6, 0.6],
       [6, 3, 3, 0.2857142857142857],
       [6, 3, 4, 0.5714285714285714],
       [6, 3, 5, 0.7142857142857143],
       [6, 4, 4, 0.8571428571428572],
       [7, 4, 5, 1.0],
       [7, 5, 5, 0.19999999999999996]], dtype=object)